# Generated by Django 4.2 on 2026-01-29 04:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import otak_aplikasi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryPengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ektraCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kode_jurusan', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('deskripsi_singkat', models.TextField(blank=True, null=True)),
                ('deskripsi_lengkap', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('gambar_utama', models.ImageField(blank=True, null=True, upload_to='jurusan/images/')),
                ('kategori', models.CharField(default='Teknologi', max_length=100)),
                ('durasi', models.CharField(default='3 Tahun', max_length=50)),
                ('jumlah_siswa', models.PositiveIntegerField(default=0)),
                ('guru_count', models.PositiveIntegerField(default=0)),
                ('lab_count', models.PositiveIntegerField(default=0)),
                ('serapan_kerja', models.CharField(default='95%', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='jurusan/logos/')),
                ('kuota', models.PositiveIntegerField(default=40)),
                ('kaprodi_nama', models.CharField(blank=True, max_length=200, null=True)),
                ('kaprodi_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kaprodi_foto', models.ImageField(blank=True, null=True, upload_to='jurusan/kaprodi/')),
                ('kontak', models.CharField(blank=True, max_length=100, null=True)),
                ('gedung', models.CharField(blank=True, max_length=100, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriStaffDanGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='newsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimoniAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jabatan', models.CharField(max_length=200)),
                ('perusahaan', models.CharField(max_length=200)),
                ('tahun_lulus', models.IntegerField()),
                ('testimoni', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='jurusan/testimoni/%Y_%m_%d')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimoni_alumni', to='otak_aplikasi.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDanGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('pendidikan', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_dan_guru/%Y_%m_%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_dan_guru', to='otak_aplikasi.kategoristaffdanguru')),
                ('mata_pelajaran', models.ManyToManyField(related_name='guru_staff', to='otak_aplikasi.matapelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('penyelenggara', models.CharField(max_length=200)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikasi', to='otak_aplikasi.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='ProspekKarir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('rata_gaji', models.CharField(blank=True, max_length=100, null=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospek_karir', to='otak_aplikasi.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('deskripsi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumuman', to='otak_aplikasi.categorypengumuman')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/%Y_%m_%d')),
                ('video', models.URLField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otak_aplikasi.newscategory')),
            ],
        ),
        migrations.CreateModel(
            name='MitraIndustri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='jurusan/mitra/')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_industri', to='otak_aplikasi.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='Kompetensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('tipe', models.CharField(choices=[('Hard', 'Hard Skill'), ('Soft', 'Soft Skill')], max_length=10)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kompetensi', to='otak_aplikasi.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='FilePengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=otak_aplikasi.models.upload_pengumuman_file)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('last_downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_pengumuman_files', to=settings.AUTH_USER_MODEL)),
                ('pengumuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='otak_aplikasi.pengumuman')),
            ],
        ),
        migrations.CreateModel(
            name='FasilitasJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('icon', models.CharField(default='computer', help_text='Material Symbols name', max_length=50)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasilitas', to='otak_aplikasi.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='ektra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('pembina', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('jadwal', models.CharField(choices=[('07.00 - 09.00', '07.00 - 09.00'), ('09.00 - 11.00', '09.00 - 11.00'), ('11.00 - 13.00', '11.00 - 13.00'), ('13.00 - 15.00', '13.00 - 15.00'), ('15.00 - 17.00', '15.00 - 17.00')], max_length=200)),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=200)),
                ('type_ektra', models.CharField(choices=[('Wajib', 'Wajib'), ('Pilihan', 'Pilihan')], max_length=200)),
                ('siswa_aktif', models.IntegerField(default=0)),
                ('pretasi', models.IntegerField(default=0)),
                ('tahun', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ektra/images/%Y_%m_%d')),
                ('video', models.URLField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otak_aplikasi.ektracategory')),
            ],
        ),
    ]
