# Generated by Django 4.2 on 2026-01-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdanguru',
            name='kategori',
        ),
        migrations.AddField(
            model_name='staffdanguru',
            name='jabatan',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='KategoriStaffDanGuru',
        ),
    ]
