# Generated by Django 4.2 on 2026-01-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSekolah',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_type', models.CharField(choices=[('SMA', 'SMA (Sekolah Menengah Atas)'), ('SMK', 'SMK (Sekolah Menengah Kejuruan)'), ('MA', 'MA (Madrasah Aliyah)'), ('SMAK', 'SMAK (Sekolah Menengah Agama Katolik)'), ('SMAS', 'SMAS (Sekolah Menengah Atas Swasta)'), ('SMKS', 'SMKS (Sekolah Menengah Kejuruan Swasta)'), ('MAS', 'MAS (Madrasah Aliyah Swasta)'), ('SLB', 'SLB (Sekolah Luar Biasa)'), ('LAINNYA', 'Lainnya')], default='SMK', max_length=10, verbose_name='Jenis Sekolah')),
                ('nama_sekolah', models.CharField(max_length=255, verbose_name='Nama Sekolah')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('npsn', models.CharField(max_length=50, unique=True, verbose_name='NPSN')),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, verbose_name='Telepon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True)),
                ('alamat', models.TextField(verbose_name='Alamat Lengkap')),
                ('status', models.CharField(choices=[('NEGERI', 'Negeri'), ('SWASTA', 'Swasta')], default='SWASTA', max_length=20, verbose_name='Status Sekolah')),
                ('accreditation', models.CharField(choices=[('A', 'A (Sangat Baik)'), ('B', 'B (Baik)'), ('C', 'C (Cukup)'), ('TT', 'Terakreditasi'), ('BT', 'Belum Terakreditasi')], max_length=10, verbose_name='Akreditasi')),
                ('accreditation_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Akreditasi')),
                ('tahun_berdiri', models.IntegerField(blank=True, null=True, verbose_name='Tahun Berdiri')),
                ('luas_tanah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Luas Tanah (m²)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Sekolah',
                'verbose_name_plural': 'Data Sekolah',
                'ordering': ['nama_sekolah'],
            },
        ),
        migrations.CreateModel(
            name='SejarahSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_singkat', models.TextField(blank=True, null=True, verbose_name='Deskripsi Singkat')),
                ('konten_lengkap', models.TextField(verbose_name='Konten Lengkap Sejarah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sekolah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sejarah', to='otak_aplikasi.datasekolah', verbose_name='Sekolah')),
            ],
            options={
                'verbose_name': 'Sejarah Sekolah',
                'verbose_name_plural': 'Sejarah Sekolah',
            },
        ),
        migrations.CreateModel(
            name='VisiMisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi_judul', models.CharField(default='Visi', max_length=100, verbose_name='Judul Visi')),
                ('visi_content', models.TextField(verbose_name='Konten Visi')),
                ('visi_periode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Periode Visi')),
                ('moto_sekolah', models.CharField(blank=True, max_length=255, null=True, verbose_name='Moto Sekolah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sekolah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visi_misi', to='otak_aplikasi.datasekolah', verbose_name='Sekolah')),
            ],
            options={
                'verbose_name': 'Visi & Misi',
                'verbose_name_plural': 'Visi & Misi',
            },
        ),
        migrations.CreateModel(
            name='TimelineSejarah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=20, verbose_name='Tahun')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Peristiwa')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('icon', models.CharField(default='event', help_text='Nama icon dari Material Symbols', max_length=50, verbose_name='Icon')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('sejarah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='otak_aplikasi.sejarahsekolah', verbose_name='Sejarah Sekolah')),
            ],
            options={
                'verbose_name': 'Timeline Sejarah',
                'verbose_name_plural': 'Timeline Sejarah',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='StrukturOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi Struktur')),
                ('struktur_image', models.ImageField(blank=True, null=True, upload_to='struktur_organisasi/', verbose_name='Gambar Struktur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sekolah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='struktur_organisasi', to='otak_aplikasi.datasekolah', verbose_name='Sekolah')),
            ],
            options={
                'verbose_name': 'Struktur Organisasi',
                'verbose_name_plural': 'Struktur Organisasi',
            },
        ),
        migrations.CreateModel(
            name='PrestasiSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('AKREDITASI', 'Akreditasi'), ('SERTIFIKASI', 'Sertifikasi'), ('PENGHARGAAN', 'Penghargaan'), ('KOMPETISI', 'Kompetisi'), ('LAINNYA', 'Lainnya')], max_length=20, verbose_name='Jenis Prestasi')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Prestasi')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('penyelenggara', models.CharField(blank=True, max_length=255, null=True, verbose_name='Penyelenggara')),
                ('tingkat', models.CharField(choices=[('SEKOLAH', 'Sekolah'), ('KOTA', 'Kota'), ('PROVINSI', 'Provinsi'), ('NASIONAL', 'Nasional'), ('INTERNASIONAL', 'Internasional')], max_length=20, verbose_name='Tingkat')),
                ('dokumen', models.FileField(blank=True, null=True, upload_to='prestasi/', verbose_name='Dokumen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='otak_aplikasi.datasekolah', verbose_name='Sekolah')),
            ],
            options={
                'verbose_name': 'Prestasi Sekolah',
                'verbose_name_plural': 'Prestasi Sekolah',
                'ordering': ['-tahun', 'jenis'],
            },
        ),
        migrations.CreateModel(
            name='Misi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('konten', models.TextField(verbose_name='Konten Misi')),
                ('icon', models.CharField(default='check_circle', help_text='Nama icon dari Material Symbols', max_length=50, verbose_name='Icon')),
                ('visi_misi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misi_items', to='otak_aplikasi.visimisi', verbose_name='Visi Misi')),
            ],
            options={
                'verbose_name': 'Item Misi',
                'verbose_name_plural': 'Item Misi',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='JabatanStruktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_jabatan', models.CharField(choices=[('KEPALA', 'Kepala Sekolah'), ('WAKASEK', 'Wakil Kepala Sekolah'), ('KEPALA_PROGRAM', 'Kepala Program Keahlian'), ('GURU', 'Guru'), ('STAFF', 'Staff'), ('LAINNYA', 'Lainnya')], max_length=20, verbose_name='Tipe Jabatan')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('gelar_depan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gelar Depan')),
                ('gelar_belakang', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gelar Belakang')),
                ('jabatan', models.CharField(max_length=255, verbose_name='Jabatan')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi Jabatan')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jabatan_struktur/', verbose_name='Foto')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('struktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jabatan_items', to='otak_aplikasi.strukturorganisasi', verbose_name='Struktur Organisasi')),
            ],
            options={
                'verbose_name': 'Jabatan Struktur',
                'verbose_name_plural': 'Jabatan Struktur',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='GuruTenagaPendidik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP')),
                ('nama_lengkap', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('jenis_tenaga', models.CharField(choices=[('GURU', 'Guru'), ('TU', 'Tenaga Administrasi'), ('PUSTAKAWAN', 'Pustakawan'), ('LABORAN', 'Laboran'), ('LAINNYA', 'Lainnya')], max_length=20, verbose_name='Jenis Tenaga')),
                ('jabatan', models.CharField(max_length=255, verbose_name='Jabatan')),
                ('bidang', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bidang')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='guru_tenaga/', verbose_name='Foto')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guru_tenaga', to='otak_aplikasi.datasekolah', verbose_name='Sekolah')),
            ],
            options={
                'verbose_name': 'Guru & Tenaga Pendidik',
                'verbose_name_plural': 'Guru & Tenaga Pendidik',
                'ordering': ['jenis_tenaga', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='FasilitasSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Fasilitas')),
                ('kategori', models.CharField(choices=[('LABORATORIUM', 'Laboratorium'), ('BENGKEL', 'Bengkel'), ('PERPUSTAKAAN', 'Perpustakaan'), ('OLAHRAGA', 'Olahraga'), ('SENI', 'Seni & Budaya'), ('IBADAH', 'Ibadah'), ('UMUM', 'Umum'), ('LAINNYA', 'Lainnya')], max_length=20, verbose_name='Kategori')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fasilitas/', verbose_name='Foto Fasilitas')),
                ('kapasitas', models.IntegerField(blank=True, null=True, verbose_name='Kapasitas')),
                ('lokasi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokasi')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('PERBAIKAN', 'Dalam Perbaikan'), ('NONAKTIF', 'Nonaktif')], default='AKTIF', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasilitas', to='otak_aplikasi.datasekolah', verbose_name='Sekolah')),
            ],
            options={
                'verbose_name': 'Fasilitas Sekolah',
                'verbose_name_plural': 'Fasilitas Sekolah',
                'ordering': ['kategori', 'nama'],
            },
        ),
    ]
