# Generated by Django 4.2 on 2026-02-01 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0002_remove_staffdanguru_kategori_staffdanguru_jabatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FasilitasLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lab', models.CharField(help_text='Nama Laboratorium', max_length=200)),
                ('deskripsi', models.TextField(help_text='Deskripsi singkat tentang laboratorium')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='fasilitas_lab/images/%Y_%m_%d')),
                ('icon', models.CharField(default='terminal', help_text='Material Symbols icon name', max_length=50)),
                ('warna_tema', models.CharField(default='blue', help_text='Warna tema untuk card (blue, purple, red, pink, green, dll)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorium', to='otak_aplikasi.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='PeralatanLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peralatan', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('Peralatan Utama', 'Peralatan Utama'), ('Fitur Tambahan', 'Fitur Tambahan'), ('Peralatan Produksi', 'Peralatan Produksi'), ('Workstation', 'Workstation'), ('Perangkat Lunak', 'Perangkat Lunak'), ('Robotika & IoT', 'Robotika & IoT')], default='Peralatan Utama', max_length=50)),
                ('fasilitas_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peralatan', to='otak_aplikasi.fasilitaslab')),
            ],
        ),
    ]
