# Generated by Django 4.2 on 2026-02-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0003_fasilitaslab_peralatanlab'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_siswa', models.IntegerField(default=0, help_text='Total siswa aktif')),
                ('persentase_pertumbuhan_siswa', models.CharField(default='+0%', help_text='Contoh: +12%', max_length=10)),
                ('progress_siswa', models.IntegerField(default=85, help_text='Progress bar (0-100)')),
                ('total_instruktur', models.IntegerField(default=0, help_text='Total instruktur profesional')),
                ('status_instruktur', models.CharField(default='Sertifikasi', help_text='Status instruktur', max_length=50)),
                ('progress_instruktur', models.IntegerField(default=95, help_text='Progress bar (0-100)')),
                ('total_mitra', models.IntegerField(default=0, help_text='Total mitra industri')),
                ('label_mitra', models.CharField(default='Perusahaan', help_text='Label untuk mitra', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Aktifkan statistik ini')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistik Sekolah',
                'verbose_name_plural': 'Statistik Sekolah',
                'ordering': ['-created_at'],
            },
        ),
    ]
