# Generated by Django 4.2 on 2026-01-14 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0003_remove_gurutenagapendidik_sekolah_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasekolah',
            old_name='nama_sekolah',
            new_name='school_name',
        ),
    ]
