# Generated by Django 4.2 on 2026-02-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0004_schoolstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolstatistics',
            name='total_mitra',
        ),
    ]
