# Generated by Django 4.2 on 2026-01-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0004_rename_nama_sekolah_datasekolah_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasekolah',
            name='level',
            field=models.CharField(choices=[('slta', 'Sekolah Lanjutan Tingkat Atas'), ('sltp', 'Sekolah Lanjutan Tingkat Pertama'), ('sd', 'Sekolah Dasar'), ('tk', 'Taman Kanak-Kanak')], default='slta', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasekolah',
            name='school_type',
            field=models.CharField(choices=[('smk', 'Sekolah Menengah Kejuruan'), ('sma', 'Sekolah Menengah Atas'), ('ma', 'Madrasah Aliyah'), ('smak', 'Sekolah Menengah Atas Katolik'), ('smas', 'Sekolah Menengah Atas Swasta'), ('smks', 'Sekolah Menengah Kejuruan Swasta'), ('mas', 'Madrasah Aliyah Swasta'), ('smp', 'Sekolah Menengah Pertama'), ('mts', 'Madrasah Tsanawiyah'), ('smpk', 'Sekolah Menengah Pertama Katolik'), ('smps', 'Sekolah Menengah Pertama Swasta'), ('mtss', 'Madrasah Tsanawiyah Swasta'), ('sd', 'Sekolah Dasar'), ('sdb', 'Sekolah Dasar Bilingual'), ('sds', 'Sekolah Dasar Swasta'), ('mi', 'Madrasah Ibtidaiyah'), ('mis', 'Madrasah Ibtidaiyah Swasta'), ('tk', 'Taman Kanak-Kanak'), ('tka', 'Taman Kanak-Kanak Aisyiyah'), ('tki', 'Taman Kanak-Kanak Islam'), ('tks', 'Taman Kanak-Kanak Swasta')], default='smk', max_length=10),
        ),
    ]
