# Generated by Django 4.2 on 2026-02-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0005_remove_schoolstatistics_total_mitra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ektra',
            old_name='pretasi',
            new_name='prestasi',
        ),
    ]
