# Generated by Django 4.2 on 2026-01-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0005_datasekolah_level_alter_datasekolah_school_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasekolah',
            name='level',
        ),
        migrations.RemoveField(
            model_name='datasekolah',
            name='school_type',
        ),
    ]
