# Generated by Django 4.2 on 2026-01-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0006_remove_datasekolah_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSekolah',
        ),
        migrations.DeleteModel(
            name='WebsiteSettings',
        ),
    ]
