# Generated by Django 4.2 on 2026-02-14 05:00

from django.db import migrations, models
import otak_aplikasi.models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0006_rename_pretasi_ektra_prestasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='penting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ektra',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=otak_aplikasi.models.ektra_upload_path),
        ),
        migrations.AlterField(
            model_name='ektra',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ektracategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fasilitaslab',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=otak_aplikasi.models.lab_upload_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=otak_aplikasi.models.news_upload_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdanguru',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=otak_aplikasi.models.staff_upload_path),
        ),
        migrations.AlterField(
            model_name='testimonialumni',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=otak_aplikasi.models.testimoni_upload_path),
        ),
    ]
