# Generated by Django 4.2 on 2026-02-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0007_pengumuman_penting_alter_ektra_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstatistics',
            name='video_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/watch?v=NCMuVN4fFgo', help_text='Masukkan link YouTube (contoh: https://www.youtube.com/watch?v=...)', max_length=500, null=True),
        ),
    ]
