# Generated by Django 4.2 on 2026-02-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0008_schoolstatistics_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolstatistics',
            name='total_instruktur',
        ),
        migrations.RemoveField(
            model_name='schoolstatistics',
            name='total_siswa',
        ),
    ]
