# Generated by Django 4.2.11 on 2026-10-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0009_remove_schoolstatistics_total_instruktur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypengumuman',
            options={'verbose_name': 'Kategori Pengumuman', 'verbose_name_plural': 'Kategori Pengumuman'},
        ),
        migrations.AlterModelOptions(
            name='ektra',
            options={'verbose_name': 'Ekstrakurikuler', 'verbose_name_plural': 'Ekstrakurikuler'},
        ),
        migrations.AlterModelOptions(
            name='ektracategory',
            options={'verbose_name': 'Kategori Ekskul', 'verbose_name_plural': 'Kategori Ekskul'},
        ),
        migrations.AlterModelOptions(
            name='fasilitaslab',
            options={'verbose_name': 'Laboratorium', 'verbose_name_plural': 'Laboratorium'},
        ),
        migrations.AlterModelOptions(
            name='filepengumuman',
            options={'verbose_name': 'File Lampiran', 'verbose_name_plural': 'File Lampiran'},
        ),
        migrations.AlterModelOptions(
            name='jurusan',
            options={'verbose_name': 'Jurusan', 'verbose_name_plural': 'Jurusan'},
        ),
        migrations.AlterModelOptions(
            name='matapelajaran',
            options={'verbose_name': 'Mata Pelajaran', 'verbose_name_plural': 'Mata Pelajaran'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Berita', 'verbose_name_plural': 'Berita'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Kategori Berita', 'verbose_name_plural': 'Kategori Berita'},
        ),
        migrations.AlterModelOptions(
            name='pengumuman',
            options={'verbose_name': 'Pengumuman', 'verbose_name_plural': 'Pengumuman'},
        ),
        migrations.AlterModelOptions(
            name='peralatanlab',
            options={'verbose_name': 'Peralatan Lab', 'verbose_name_plural': 'Peralatan Lab'},
        ),
        migrations.AlterModelOptions(
            name='staffdanguru',
            options={'verbose_name': 'Guru & Staff', 'verbose_name_plural': 'Guru & Staff'},
        ),
    ]
