# Generated by Django 4.2 on 2026-01-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0009_alter_berita_created_at_alter_berita_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Gambar cover utama untuk berita', null=True, upload_to='berita/cover/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Tampilkan di halaman utama'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='is_latest',
            field=models.BooleanField(default=False, help_text='Berita terbaru'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Berita populer'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Berita trending'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Caption untuk gambar', max_length=255),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='gambar',
            field=models.ImageField(help_text='Upload gambar untuk berita', upload_to='berita/gambar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Centang jika ini gambar utama (hanya satu yang bisa jadi primary)'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Urutan tampil gambar (0 pertama, 1 kedua, dst)'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
