# Generated by Django 4.2 on 2026-01-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0010_alter_berita_cover_image_alter_berita_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsimage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='berita',
        ),
        migrations.DeleteModel(
            name='Berita',
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
