# Generated by Django 4.2 on 2026-01-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ektraCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ektra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('pembina', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('jadwal', models.CharField(choices=[('07.00 - 09.00', '07.00 - 09.00'), ('09.00 - 11.00', '09.00 - 11.00'), ('11.00 - 13.00', '11.00 - 13.00'), ('13.00 - 15.00', '13.00 - 15.00'), ('15.00 - 17.00', '15.00 - 17.00')], max_length=200)),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=200)),
                ('type_ektra', models.CharField(choices=[('Wajib', 'Wajib'), ('Pilihan', 'Pilihan')], max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ektra/images/%Y_%m_%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='ektra/videos/%Y_%m_%d')),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otak_aplikasi.ektracategory')),
            ],
        ),
    ]
