# Generated by Django 4.2 on 2026-01-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0013_ektracategory_alter_news_slug_ektra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ektra',
            name='pretasi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ektra',
            name='siswa_aktif',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ektra',
            name='tahun',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
