# Generated by Django 4.2 on 2026-01-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0014_ektra_pretasi_ektra_siswa_aktif_ektra_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='ektra',
            name='lokasi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
