# Generated by Django 4.2 on 2026-01-15 05:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0015_ektra_lokasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FasilitasJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('icon', models.CharField(default='computer', max_length=50)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='jurusan/fasilitas/')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasilitas', to='otak_aplikasi.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Fasilitas Jurusan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='guru/')),
                ('nip', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('jabatan', models.CharField(default='Guru', max_length=100)),
                ('bidang_keahlian', models.CharField(max_length=200)),
                ('pengalaman', models.IntegerField(default=0, help_text='Tahun pengalaman')),
                ('sertifikasi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['jabatan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('kode_jurusan', models.CharField(max_length=20, unique=True)),
                ('kategori', models.CharField(default='Teknologi', max_length=100)),
                ('deskripsi_singkat', models.TextField(max_length=500)),
                ('deskripsi_lengkap', ckeditor.fields.RichTextField()),
                ('gambar_utama', models.ImageField(blank=True, null=True, upload_to='jurusan/gambar_utama/')),
                ('video_profil', models.FileField(blank=True, null=True, upload_to='jurusan/video/')),
                ('jumlah_siswa', models.IntegerField(default=0)),
                ('guru_count', models.IntegerField(default=0)),
                ('lab_count', models.IntegerField(default=0)),
                ('serapan_kerja', models.CharField(default='95%', max_length=10)),
                ('durasi', models.CharField(default='3 Tahun', max_length=50)),
                ('icon', models.CharField(default='terminal', help_text='Material Symbols name', max_length=50)),
                ('kuota', models.PositiveIntegerField(default=40)),
                # Kaprodi info
                ('kaprodi_nama', models.CharField(blank=True, max_length=200, null=True)),
                ('kaprodi_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kaprodi_foto', models.ImageField(blank=True, null=True, upload_to='jurusan/kaprodi/')),
                ('kontak', models.CharField(blank=True, max_length=100, null=True)),
                ('gedung', models.CharField(default='Gedung A Lt. 2', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kaprodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurusan_dipimpin', to='otak_aplikasi.guru')),
            ],
            options={
                'verbose_name_plural': 'Jurusan',
                'ordering': ['view_count', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Kompetensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('tipe', models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], default='hard', max_length=10)),
                ('deskripsi', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kompetensi',
                'ordering': ['tipe', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='MitraIndustri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='jurusan/mitra/')),
                ('website', models.URLField(blank=True)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Mitra Industri',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Sertifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('penyelenggara', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='jurusan/sertifikasi/')),
                ('deskripsi', models.TextField(blank=True)),
                ('biaya', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sertifikasi',
                'ordering': ['penyelenggara', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='TestimoniAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jurusan/alumni/')),
                ('perusahaan', models.CharField(max_length=200)),
                ('jabatan', models.CharField(max_length=200)),
                ('tahun_lulus', models.IntegerField()),
                ('testimoni', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimoni_alumni', to='otak_aplikasi.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Testimoni Alumni',
                'ordering': ['-tahun_lulus', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='ProspekKarir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('rata_gaji', models.CharField(blank=True, max_length=100)),
                ('tingkat_permintaan', models.IntegerField(choices=[(1, 'Rendah'), (2, 'Sedang'), (3, 'Tinggi')], default=1)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospek_karir', to='otak_aplikasi.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Prospek Karir',
                'ordering': ['-tingkat_permintaan', 'posisi'],
            },
        ),
        migrations.CreateModel(
            name='PrestasiJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('nama_prestasi', models.CharField(max_length=300)),
                ('tingkat', models.CharField(choices=[('sekolah', 'Sekolah'), ('kota', 'Kota/Kabupaten'), ('provinsi', 'Provinsi'), ('nasional', 'Nasional'), ('internasional', 'Internasional')], max_length=100)),
                ('penyelenggara', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('dokumentasi', models.ImageField(blank=True, null=True, upload_to='jurusan/prestasi/')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='otak_aplikasi.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Prestasi Jurusan',
                'ordering': ['-tahun', '-id'],
            },
        ),
        migrations.AddField(
            model_name='jurusan',
            name='kompetensi_hard',
            field=models.ManyToManyField(blank=True, related_name='jurusan_hard', to='otak_aplikasi.kompetensi'),
        ),
        migrations.AddField(
            model_name='jurusan',
            name='kompetensi_soft',
            field=models.ManyToManyField(blank=True, related_name='jurusan_soft', to='otak_aplikasi.kompetensi'),
        ),
        migrations.AddField(
            model_name='jurusan',
            name='mitra_industri',
            field=models.ManyToManyField(blank=True, related_name='jurusan', to='otak_aplikasi.mitraindustri'),
        ),
        migrations.AddField(
            model_name='jurusan',
            name='sertifikasi',
            field=models.ManyToManyField(blank=True, related_name='jurusan', to='otak_aplikasi.sertifikasi'),
        ),
        migrations.CreateModel(
            name='GaleriJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='jurusan/galeri/')),
                ('deskripsi', models.TextField(blank=True)),
                ('tipe', models.CharField(choices=[('lab', 'Laboratorium'), ('praktik', 'Kegiatan Praktik'), ('event', 'Acara'), ('prestasi', 'Prestasi'), ('lainnya', 'Lainnya')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='otak_aplikasi.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Galeri Jurusan',
                'ordering': ['-created_at'],
            },
        ),
    ]
