# Generated by Django 4.2 on 2026-01-20 03:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0017_remove_galerijurusan_jurusan_remove_jurusan_kaprodi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ektra',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
