# Generated by Django 4.2 on 2026-01-20 06:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0019_fix_schema_manually'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='galerijurusan',
        #     name='jurusan',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Guru',
                ),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS otak_aplikasi_guru;"),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='prestasijurusan',
        #     name='jurusan',
        # ),
        migrations.AlterModelOptions(
            name='fasilitasjurusan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jurusan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kompetensi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mitraindustri',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prospekkarir',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sertifikasi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testimonialumni',
            options={},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='fasilitasjurusan',
                    name='gambar',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='jurusan',
                    name='is_active',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='jurusan',
                    name='kompetensi_hard',
                ),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS otak_aplikasi_jurusan_kompetensi_hard;"),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='jurusan',
                    name='kompetensi_soft',
                ),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS otak_aplikasi_jurusan_kompetensi_soft;"),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='jurusan',
                    name='mitra_industri',
                ),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS otak_aplikasi_jurusan_mitra_industri;"),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='jurusan',
                    name='sertifikasi',
                ),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS otak_aplikasi_jurusan_sertifikasi;"),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='jurusan',
                    name='video_profil',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='kompetensi',
                    name='deskripsi',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='kompetensi',
                    name='icon',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='mitraindustri',
                    name='deskripsi',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='mitraindustri',
                    name='website',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='prospekkarir',
                    name='tingkat_permintaan',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='sertifikasi',
                    name='biaya',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='sertifikasi',
                    name='deskripsi',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='sertifikasi',
                    name='logo',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='testimonialumni',
                    name='created_at',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='testimonialumni',
                    name='is_active',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='testimonialumni',
                    name='rating',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='kompetensi',
            name='jurusan',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='kompetensi', to='otak_aplikasi.jurusan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitraindustri',
            name='jurusan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='mitra_industri', to='otak_aplikasi.jurusan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertifikasi',
            name='jurusan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sertifikasi', to='otak_aplikasi.jurusan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ektra',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ektra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ektracategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fasilitasjurusan',
            name='icon',
            field=models.CharField(default='computer', help_text='Material Symbols name', max_length=50),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='deskripsi_lengkap',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='deskripsi_singkat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='gambar_utama',
            field=models.ImageField(blank=True, null=True, upload_to='jurusan/images/'),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='gedung',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='guru_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='jumlah_siswa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='kode_jurusan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='lab_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kompetensi',
            name='tipe',
            field=models.CharField(choices=[('Hard', 'Hard Skill'), ('Soft', 'Soft Skill')], max_length=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testimonialumni',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jurusan/testimoni/'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='GaleriJurusan',
                ),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS otak_aplikasi_galerijurusan;"),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='PrestasiJurusan',
                ),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS otak_aplikasi_prestasijurusan;"),
            ],
        ),
    ]
