# Generated by Django 4.2 on 2026-01-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0023_alter_news_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurusan',
            name='icon',
        ),
        migrations.AddField(
            model_name='jurusan',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='jurusan/logos/'),
        ),
    ]
