# Generated by Django 4.2 on 2026-01-26 02:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0024_remove_jurusan_icon_jurusan_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryPengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('deskripsi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumuman', to='otak_aplikasi.categorypengumuman')),
            ],
        ),
        migrations.CreateModel(
            name='FilePengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='pengumuman/files/')),
                ('pengumuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='otak_aplikasi.pengumuman')),
            ],
        ),
    ]
