# Generated by Django 4.2 on 2026-01-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0025_categorypengumuman_pengumuman_filepengumuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
