"""
Django settings for web_smknj project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fu*ct8a+b@1h&!0a5rx%5xsunc9e^g!hnc5g0tmdcb)%a_4fw0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.19', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig', 
    'ckeditor',
    'ckeditor_uploader',
    'otak_aplikasi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_smknj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_smknj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'web_smknj_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'id-id'
TIME_ZONE = 'Asia/Jakarta'  # PASTIKAN INI BENAR
USE_I18N = True
USE_L10N = True
USE_TZ = True  # PASTIKAN INI TRUE


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # untuk production

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Additional cache for sessions if needed
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# Leader titles configuration
LEADER_TITLES = [
    'Kepala Sekolah',
    'Waka bidang Sarana dan Prasarana',
    'Waka bidang Kurikulum',
    'Waka bidang Hubungan Masyarakat',
    'Waka bidang Kesiswaan'
]

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

JAZZMIN_SETTINGS = {
  "site_title": "Admin SMK Nurul Jadid",
  "site_header": "Dashboard SMK",
  "site_brand": "SMK NJ",
  "site_logo": "images/logo/logo.png",
  "welcome_sign": "Welcome to the Admin SMK Nurul Jadid",
  "copyright": "SMK Nurul Jadid",
  "topmenu_links": [
    {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
    {"app": "otak_aplikasi"},
  ],
  "show_ui_builder": True,
  "custom_css": "static/css/jazzmin-custom.css",
  "custom_js": "js/admin-hash-tabs.js",
  "hide_apps": ["auth"],
  "icons": {
    "otak_aplikasi.news": "fas fa-newspaper",
    "otak_aplikasi.newsCategory": "fas fa-tags",
    "otak_aplikasi.Pengumuman": "fas fa-bullhorn",
    "otak_aplikasi.categoryPengumuman": "fas fa-folder",
    "otak_aplikasi.FilePengumuman": "fas fa-file-download",
    "otak_aplikasi.Jurusan": "fas fa-graduation-cap",
    "otak_aplikasi.StaffDanGuru": "fas fa-users-cog",
    "otak_aplikasi.MataPelajaran": "fas fa-book",
    "otak_aplikasi.ektra": "fas fa-running",
    "otak_aplikasi.ektraCategory": "fas fa-list",
    "otak_aplikasi.FasilitasLab": "fas fa-flask",
    "otak_aplikasi.PeralatanLab": "fas fa-tools",
    "otak_aplikasi.SchoolStatistics": "fas fa-chart-line",
    "otak_aplikasi.MitraIndustri": "fas fa-handshake",
  },
  "order_with_respect_to": [
    "otak_aplikasi.SchoolStatistics",
    "otak_aplikasi.news",
    "otak_aplikasi.newsCategory",
    "otak_aplikasi.Pengumuman",
    "otak_aplikasi.categoryPengumuman",
    "otak_aplikasi.Jurusan",
    "otak_aplikasi.StaffDanGuru",
    "otak_aplikasi.MataPelajaran",
    "otak_aplikasi.ektra",
    "otak_aplikasi.ektraCategory",
    "otak_aplikasi.FasilitasLab",
  ],
}


# Email Configuration
# Default to console backend for development
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Untuk production/sending real emails via Gmail:
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'alamatkeemailpengirim@gmail.com'  # Ganti dengan email pengirim
#EMAIL_HOST_USER = [EMAIL_ADDRESS]' # Ganti dengan email asli anda untuk mengirim
# EMAIL_HOST_PASSWORD = 'password_app_anda'  # App Password, bukan password email biasa
#EMAIL_HOST_PASSWORD = 'password_app_anda' # Ganti dengan App Password anda
# RECIPIENT_ADDRESS = 'smknurja.paiton@gmail.com'
#RECIPIENT_ADDRESS = 'smknurja.paiton@gmail.com'


